{"name": "test_add[get_add_datas3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -0.1 == 0.3", "trace": "self = <testing.test_calc.TestCalc object at 0x0000028DE44B1A90>, get_add_datas = [0.1, -0.2, 0.3]\n\n    @allure.story(\"加法模块\")\n    @pytest.mark.run(order=1)\n    def test_add(self,get_add_datas):\n       with allure.step(\"计算两个数相加\"):\n          calc = Calculator()\n          result = calc.add(get_add_datas[0],get_add_datas[1])\n          if isinstance(result, float):\n             result = round(result, 2)\n             # 得到相加结果之后写断言\n>         assert result == get_add_datas[2]\nE         assert -0.1 == 0.3\n\ntest_calc.py:42: AssertionError"}, "steps": [{"name": "计算两个数相加", "status": "failed", "statusDetails": {"message": "AssertionError: assert -0.1 == 0.3\n", "trace": "  File \"D:\\PycharmProjects\\pythonProject\\pytestWork\\testing\\test_calc.py\", line 42, in test_add\n    assert result == get_add_datas[2]\n"}, "start": 1614735996833, "stop": 1614735996833}], "parameters": [{"name": "get_add_datas", "value": "[0.1, -0.2, 0.3]"}], "start": 1614735996833, "stop": 1614735996834, "uuid": "34ad89a4-02b3-4942-af75-acab401c8854", "historyId": "0177bcc62627c23f0937723bdb57406c", "testCaseId": "a7b29b08300809261dc069b49da8543b", "fullName": "test_calc.TestCalc#test_add", "labels": [{"name": "story", "value": "加法模块"}, {"name": "feature", "value": "计算器"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LHTC1CQRZC5VGE5"}, {"name": "thread", "value": "3732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}