{"name": "test_add[get_datas3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -0.1 == 0.3", "trace": "self = <testing.test_calc.TestCalc object at 0x000002E2BCA8B190>, get_datas = [0.1, -0.2, 0.3]\n\n    @allure.story(\"加法模块\")\n    @pytest.mark.run(order=1)\n    def test_add(self,get_datas):\n       with allure.step(\"计算两个数相加\"):\n          calc = Calculator()\n          result = calc.add(get_datas[0],get_datas[1])\n          if isinstance(result, float):\n             result = round(result, 2)\n             # 得到相加结果之后写断言\n>         assert result == get_datas[2]\nE         assert -0.1 == 0.3\n\ntest_calc.py:36: AssertionError"}, "steps": [{"name": "计算两个数相加", "status": "failed", "statusDetails": {"message": "AssertionError: assert -0.1 == 0.3\n", "trace": "  File \"D:\\PycharmProjects\\pythonProject\\pytestWork\\testing\\test_calc.py\", line 36, in test_add\n    assert result == get_datas[2]\n"}, "start": 1614692316651, "stop": 1614692316652}], "parameters": [{"name": "get_datas", "value": "[0.1, -0.2, 0.3]"}], "start": 1614692316651, "stop": 1614692316652, "uuid": "af4fea16-95ee-4d6d-9460-5d8a9044c09d", "historyId": "476d39602eb18d39341b499763a20c08", "testCaseId": "a7b29b08300809261dc069b49da8543b", "fullName": "test_calc.TestCalc#test_add", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "加法模块"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LHTC1CQRZC5VGE5"}, {"name": "thread", "value": "12136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}